/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddModelModal: typeof import('./src/components/AddModelModal.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    EditorPanel: typeof import('./src/components/EditorPanel.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneCanvas: typeof import('./src/components/SceneCanvas.vue')['default']
  }
}
